# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=600, verbose_name='Описание')),
                ('balance', models.IntegerField(default=0, editable=False, verbose_name='Баланс')),
                ('mail_1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='mail_1')),
                ('mail_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='mail_2')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона')),
                ('sms_phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер для отправки СМС')),
                ('contact_name', models.TextField(blank=True, max_length=200, verbose_name='Контакты')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Поставщик')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрывать')),
                ('orders_count', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='КЗ')),
                ('shipments_count', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Количесвто отгрузок')),
                ('regions', models.ManyToManyField(to='product_app.ProductGeo')),
            ],
            options={
                'verbose_name': 'Поставщик',
                'verbose_name_plural': 'Поставщики',
                'ordering': ['-orders_count', '-shipments_count', 'name'],
            },
        ),
    ]
