# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, verbose_name='Имя')),
                ('contact_name', models.TextField(max_length=400, verbose_name='Контактное лицо')),
                ('phone_number', models.CharField(max_length=12, null=True, verbose_name='Телефон')),
                ('mail_1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='mail_1')),
                ('mail_2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='mail_2')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрывать поставщика')),
                ('geom', djgeojson.fields.PolygonField(default='[]')),
                ('balance', models.IntegerField(default=0, editable=False, verbose_name='Баланс')),
                ('orders_count', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='КЗ')),
                ('shipments_count', models.IntegerField(db_index=True, default=0, editable=False, verbose_name='Количесвто отгрузок')),
                ('products', models.ManyToManyField(to='order_app.Product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name_plural': 'Поставщики',
                'ordering': ['-orders_count', '-shipments_count', 'name'],
                'verbose_name': 'Поставщик',
            },
        ),
    ]
