# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_app', '0003_auto_20171118_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='inn',
            field=models.TextField(db_index=True, default=None, max_length=20, null=True, unique=True, verbose_name='ИНН'),
        ),
    ]
