# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.IntegerField(default=3, verbose_name='Объем')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('CRTD', 'Создан'), ('PRCSD', 'В обработке'), ('CMPLTD', 'Обработан')], default='Создан', max_length=7, verbose_name='Статус')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=12, null=True, verbose_name='Телефон')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Адрес')),
                ('tonar', models.IntegerField(choices=[(0, 'Нет'), (1, 'ДА')], default='Нет', verbose_name='Тонары')),
                ('time_of_receipt', models.IntegerField(choices=[(0, 'День'), (1, 'Ночь'), (2, 'Круглосуточно')], default='День', verbose_name='Время приема')),
                ('payment', models.IntegerField(choices=[(1, 'Наличный'), (0, 'Безналичный')], default='Наличный', verbose_name='Расчет')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('time_completed', models.DateTimeField(blank=True, null=True, verbose_name='Дата обработки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'verbose_name': 'Заказ',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Наименования',
                'verbose_name': 'Наименование',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='has_app.Product'),
        ),
    ]
