# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('has_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='has_app.Provider', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CRTD', 'Создан'), ('PRCSG', 'В обработке'), ('CMPLTD', 'Обработан')], default='CRTD', max_length=7, verbose_name='Статус'),
        ),
    ]
