# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('has_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='time_update',
            new_name='time_updated',
        ),
    ]
