# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-09 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('has_app', '0002_auto_20170808_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='phone_number',
            field=models.CharField(max_length=60, null=True, verbose_name='Телефон'),
        ),
    ]

