# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-25 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('has_app', '0002_auto_20170725_1542'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='author',
            new_name='manager',
        ),
    ]
