# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 19:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('has_app', '0004_provider_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='geo_json',
        ),
    ]
