# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('has_app', '0005_remove_provider_geo_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='mail_1',
            field=models.EmailField(default='zaibandr@ya.ru', max_length=254, verbose_name='mail_1'),
        ),
        migrations.AddField(
            model_name='provider',
            name='mail_2',
            field=models.EmailField(default='zaibandr@ya.ru', max_length=254, verbose_name='mail_2'),
        ),
    ]
