# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('has_app', '0006_auto_20170814_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='mail_1',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='mail_1'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='mail_2',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='mail_2'),
        ),
    ]

