# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 18:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('has_app', '0007_auto_20170814_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='contact_name',
            field=models.TextField(max_length=600, verbose_name='Контактное лицо'),
        ),
    ]
