# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('has_app', '0011_auto_20170817_2317'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp', models.TextField(max_length=600)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='has_app.Order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='has_app.Provider')),
            ],
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Наименование', 'verbose_name_plural': 'Наименования'},
        ),
    ]
