# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('has_app', '0013_auto_20170829_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsnotify',
            name='cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CRTD', 'Создан'), ('CMPLTD', 'Обработан')], default='CRTD', max_length=7, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='contact_name',
            field=models.TextField(max_length=400, verbose_name='Контактное лицо'),
        ),
    ]
