# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 19:21
from __future__ import unicode_literals

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PickPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=600, verbose_name='Описание')),
                ('pick_point', djgeojson.fields.PointField()),
            ],
            options={
                'verbose_name_plural': 'Пункы самовывоза',
                'verbose_name': 'Пунк самовывоза',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=300, verbose_name='Наименование')),
            ],
            options={
                'verbose_name_plural': 'Наименования',
                'ordering': ['name'],
                'verbose_name': 'Наименование',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=600, verbose_name='Описание')),
                ('delivery_region', djgeojson.fields.PolygonField(default='[]')),
                ('products', models.ManyToManyField(db_index=True, to='product_app.Product', verbose_name='Продукция')),
            ],
            options={
                'verbose_name_plural': 'Области доставок',
                'verbose_name': 'Область доставки',
            },
        ),
        migrations.AddField(
            model_name='pickpoint',
            name='products',
            field=models.ManyToManyField(db_index=True, to='product_app.Product', verbose_name='Продукция'),
        ),
    ]


