# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productgeo',
            name='products',
            field=models.ManyToManyField(db_index=True, to='product_app.Product', verbose_name='Продукция'),
        ),
    ]
