# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='Сумма')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата Создания')),
                ('paid_date', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата оплаты')),
                ('balance_add', models.BooleanField(default=False, editable=False)),
                ('balance_take_down', models.BooleanField(default=False, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Доверительные платежи',
                'verbose_name': 'Доверительный платеж',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=600, verbose_name='Описание')),
                ('balance', models.IntegerField(default=0, editable=False, verbose_name='Баланс')),
                ('phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер телефона')),
                ('sms_phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер для отправки СМС')),
                ('contact_name', models.TextField(blank=True, max_length=200, verbose_name='Контакты')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Имя')),
                ('individual_person', models.BooleanField(default=False, verbose_name='Физическое лицо')),
            ],
            options={
                'verbose_name_plural': 'Заказчики',
                'verbose_name': 'Заказчик',
            },
        ),
        migrations.AddField(
            model_name='creditpayment',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.Customer'),
        ),
    ]
