# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 19:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='saldo_credit',
            field=models.IntegerField(default=0, verbose_name='Сальдо кредит'),
        ),
        migrations.AddField(
            model_name='customer',
            name='saldo_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Салбдо дата'),
        ),
        migrations.AddField(
            model_name='customer',
            name='saldo_debet',
            field=models.IntegerField(default=0, verbose_name='Сальдо дебет'),
        ),
    ]
