# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-18 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0002_auto_20171109_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.FloatField(default=0, editable=False, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='saldo_credit',
            field=models.FloatField(default=0, verbose_name='Сальдо кредит'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='saldo_debet',
            field=models.FloatField(default=0, verbose_name='Сальдо дебет'),
        ),
    ]
