# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_app', '0004_customer_inn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='inn',
            field=models.CharField(db_index=True, default=None, max_length=20, null=True, unique=True, verbose_name='ИНН'),
        ),
    ]
