# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider_app', '0001_initial'),
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsNotify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sms_id', models.IntegerField(default=0)),
                ('cost', models.IntegerField(default=0)),
                ('time_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order_app.Order')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_app.Provider')),
            ],
            options={
                'verbose_name_plural': 'СМС уведомления',
                'verbose_name': 'СМС уведомление',
            },
        ),
    ]

