# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider_app', '0001_initial'),
        ('customer_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeCustomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, 'Пополнение'), (0, 'Снятие')], verbose_name='Операция')),
                ('value', models.FloatField(verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.Customer')),
            ],
            options={
                'verbose_name': 'Выписка заказчика',
                'verbose_name_plural': 'Выписки заказчика',
            },
        ),
        migrations.CreateModel(
            name='DischargeInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/%Y/%m/%d/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Выписка Банка',
                'verbose_name_plural': 'Выписки Банка',
            },
        ),
        migrations.CreateModel(
            name='DischargeProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.IntegerField(choices=[(1, 'Пополнение'), (0, 'Снятие')], verbose_name='Операция')),
                ('value', models.FloatField(verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider_app.Provider')),
            ],
            options={
                'verbose_name': 'Выписка поставщика',
                'verbose_name_plural': 'Выписки поставщика',
            },
        ),
    ]
