# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 22:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discharge_app', '0002_auto_20171029_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dischargecustomer',
            name='action_date',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='dischargecustomer',
            name='document_id',
            field=models.IntegerField(blank=True, default=None, unique=True, verbose_name='№ документа'),
        ),
        migrations.AlterField(
            model_name='dischargeprovider',
            name='action_date',
            field=models.CharField(blank=True, default=None, max_length=20, verbose_name='Дата операции'),
        ),
        migrations.AlterField(
            model_name='dischargeprovider',
            name='document_id',
            field=models.IntegerField(blank=True, default=None, unique=True, verbose_name='№ документа'),
        ),
    ]


