# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0001_initial'),
        ('discharge_app', '0003_auto_20171029_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='dischargecustomer',
            name='shipment_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment_app.Shipment', verbose_name='№ отгрузки'),
        ),
        migrations.AddField(
            model_name='dischargeprovider',
            name='shipment_id',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='shipment_app.Shipment', verbose_name='№ отгрузки'),
        ),
    ]
