# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discharge_app', '0004_auto_20171029_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='DischargeEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_id', models.IntegerField(blank=True, default=None, unique=True, verbose_name='№ документа')),
                ('debet', models.FloatField(verbose_name='Дебет')),
                ('credit', models.FloatField(verbose_name='Кредит')),
                ('action_date', models.CharField(blank=True, default=None, max_length=20, verbose_name='Дата операции')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name_plural': 'Выписки Банка',
                'verbose_name': 'Выписка Банка',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Наименование')),
                ('inn', models.TextField(db_index=True, default=None, max_length=20, null=True, unique=True,
                                         verbose_name='ИНН')),
            ],
            options={
                'verbose_name_plural': 'Контрагенты',
                'verbose_name': 'Контрагент',
            },
        ),
        migrations.AlterModelOptions(
            name='dischargeinput',
            options={'verbose_name': 'Файл Выписки Банка', 'verbose_name_plural': 'Файлы Выписок Банка'},
        ),
        migrations.RemoveField(
            model_name='dischargecustomer',
            name='document_id',
        ),
        migrations.RemoveField(
            model_name='dischargeprovider',
            name='document_id',
        ),
        migrations.AddField(
            model_name='dischargeentity',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discharge_app.Entity'),
        ),
    ]


