# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discharge_app', '0005_auto_20171125_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dischargecustomer',
            options={'verbose_name': 'Выписка заказчика (приход)', 'verbose_name_plural': 'Выписки заказчика (приходы)'},
        ),
        migrations.AlterModelOptions(
            name='dischargeprovider',
            options={'verbose_name': 'Выписка поставщика (расход)', 'verbose_name_plural': 'Выписки поставщика (расходы)'},
        ),
    ]
