# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 19:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product_app', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('provider_app', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Адрес')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('coordinate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты')),
                ('tonar', models.CharField(choices=[('t', 'Да'), ('f', 'Нет')], default='t', max_length=2,
                                           verbose_name='Тонары')),
                ('time_of_receipt',
                 models.CharField(choices=[('B', 'Круглосуточно'), ('D', 'День'), ('N', 'Ночь')], default='B',
                                  max_length=2, verbose_name='Время приема')),
                ('status',
                 models.CharField(choices=[('CR', 'Создан'), ('CM', 'Обработан')], db_index=True, default='CR',
                                  max_length=7, verbose_name='Статус')),
                ('volume', models.IntegerField(default=10, verbose_name='Объем')),
                ('payment',
                 models.CharField(choices=[('f', 'Безналичный'), ('t', 'Наличный')], default='f', max_length=2,
                                  verbose_name='Расчет')),
                ('cost', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('pick_cost', models.IntegerField(default=0, verbose_name='Стоимость самовывоза')),
                ('delivery_cost', models.IntegerField(default=0, verbose_name='Стоимость c доставкой')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('phone_number', models.CharField(max_length=60, null=True, verbose_name='Телефон')),
                ('time_completed',
                 models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Дата обработки')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_app.Product')),
                ('provider',
                 models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='provider_app.Provider',
                                   verbose_name='Поставщик')),
            ],
            options={
                'verbose_name_plural': 'Заказы',
                'verbose_name': 'Заказ',
            },
        ),
    ]

