# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-25 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='provider_app.Provider', verbose_name='Поставщик'),
        ),
    ]
