# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Стоимость c доставкой'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pick_cost',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Стоимость самовывоза'),
        ),
    ]