# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-09 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0002_auto_20171029_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='provider',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='provider_app.Provider', verbose_name='Поставщик'),
        ),
    ]
