# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 22:06
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_app', '0003_auto_20171109_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='attributes',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}, verbose_name='Атрибуты'),
        ),
    ]
