# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-28 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('provider_app', '0001_initial'),
        ('customer_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('modified', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Дата изменения')),
                ('description', models.TextField(blank=True, max_length=600, verbose_name='Описание')),
                ('address', models.CharField(max_length=200, null=True, verbose_name='Адрес')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='Долгота')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='Широта')),
                ('coordinate', models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты')),
                ('transporter', models.CharField(max_length=100, verbose_name='Перевозчик')),
                ('status',
                 models.CharField(choices=[('CR', 'Создан'), ('DL', 'Доставлен'), ('CN', 'Подтвержден')], default='CR',
                                  max_length=7, verbose_name='Статус')),
                ('volume', models.IntegerField(default=10, verbose_name='Объем')),
                ('cost_in', models.IntegerField(default=0, verbose_name='Цена (входящая)')),
                ('cost_out', models.IntegerField(default=0, verbose_name='Цена (продажная)')),
                ('price_delivery', models.IntegerField(default=0, verbose_name='Стоймость доставки')),
                ('price_total', models.IntegerField(default=0, editable=False, verbose_name='Общая стоймость')),
                ('profit', models.IntegerField(default=0, editable=False, verbose_name='Прибыль')),
                ('delivered', models.DateTimeField(blank=True, null=True, verbose_name='Дата доставки')),
                ('confirmed', models.DateTimeField(blank=True, null=True, verbose_name='Дата Подтверждения')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_app.Customer',
                                               verbose_name='Покупатель')),
                ('product',
                 models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_app.Product')),
                ('provider',
                 models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='provider_app.Provider',
                                   verbose_name='Поставщик')),
            ],
            options={
                'verbose_name_plural': 'Отгрузки',
                'verbose_name': 'Отгрузка',
            },
        ),
    ]


