# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-29 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='confidant',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Доверенное лицо'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='stamp',
            field=models.NullBooleanField(verbose_name='Штамп/печать'),
        ),
    ]
