# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-22 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0004_auto_20171110_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='volume_b',
            field=models.IntegerField(default=0, verbose_name='Объем (Б)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='volume_m',
            field=models.IntegerField(default=10, verbose_name='Объем (М)'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='volume_s',
            field=models.IntegerField(default=0, verbose_name='Объем (С)'),
        ),
    ]
