# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipment_app', '0006_auto_20171130_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='documents_returned',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='have_document',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='invoice_number',
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_document',
            field=models.CharField(choices=[('Y', 'Есть'), ('N', 'Нет'), ('N', 'Скан')], default='N', max_length=4, verbose_name='Документы от заказчика'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_invoice_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Номер счет-фактуры заказчика'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='provider_document',
            field=models.CharField(choices=[('Y', 'Есть'), ('N', 'Нет'), ('N', 'Скан')], default='N', max_length=4, verbose_name='Документы от поставщика'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='provider_invoice_number',
            field=models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='Номер счет-фактуры поставшика'),
        ),
    ]
